--- Makefile	1970-01-01 01:00:00.000000000 +0100
+++ Makefile	2016-11-10 17:31:08.686722661 +0000
@@ -0,0 +1,14 @@
+all:	libaltaircam.pc
+
+%.pc:	%.pc.in
+	sed -e "s!@LIBDIR@!$(LIBDIR)!g" \
+		-e "s!@VERSION@!$(VERSION)!g" < $< > $@
+
+install:
+	mkdir -p $(LIBDIR) $(INCDIR) $(PKGCONFDIR) $(UDEVDIR)
+	case $(DEB_BUILD_ARCH) in \
+	amd64) \
+		cp $(SRCDIR)/linux/x64/libaltaircam*.so.$(VERSION) $(LIBDIR);; \
+	esac
+	ln -sf libaltaircam.so.$(VERSION) $(LIBDIR)/libaltaircam.so.$(MAJOR_REV)
+	cp $(SRCDIR)/libaltaircam.pc $(PKGCONFDIR)
